### ISSUE TITLE
Error when using schard::h5ad2seurat

### ISSUE THREAD

**Issue by SNOL2** [cellgeni/schard#3]
Hi, thanks for developing this tool! I was encountering an error when using schard::h5ad2seurat function. The size of the anndata is about 1.1 million cells.
![image](https://github.com/cellgeni/schard/assets/116245252/968dda36-13d4-4e24-a703-e7133387da80)

**Comment by iaaka** [comment]
Yep, unfortunatelly there is no way to load such large datasets into Seurat
