### ISSUE TITLE
The h5ad seems to contain multiple visium samples but library is not specified correctly in adata.obs. There should be a column that matches keys is adata.uns.spatial. (after cell2location)

### ISSUE THREAD

**Issue by huiyijiangling** [cellgeni/schard#7]
I try to load a h5ad saved after cell2location without other operations.
visx=schard::h5ad2seurat_spatial('cell2location.spatial.scRNA.h5ad')
Error:
The h5ad seems to contain multiple visium samples but library is not specified correctly in adata.obs. There should be a column that matches keys is adata.uns.spatial.

**Comment by huiyijiangling** [comment]
Using raw adata before cell2location is ok
visx=schard::h5ad2seurat_spatial('raw.before.cell2location.spatial.h5ad')
Could you help me solve that problem?

**Comment by huiyijiangling** [comment]
![image](https://github.com/cellgeni/schard/assets/51966240/3d95ae96-db12-485f-895d-ed1342c9ebc4)
Raw
![image](https://github.com/cellgeni/schard/assets/51966240/88392bda-78ab-4709-9a6b-96e9f1610241)
After cell2location

**Comment by iaaka** [comment]
Hi @huiyijiangling, looks like you have just one sample, right? can you show output of `adata.uns['spatial'].keys()` for both adatas - before and after c2l?
Is there any chance you can share whole h5ad?

**Comment by huiyijiangling** [comment]
![image](https://github.com/cellgeni/schard/assets/51966240/3d95ae96-db12-485f-895d-ed1342c9ebc4)
After cell2location

**Comment by huiyijiangling** [comment]
> Hi @huiyijiangling, looks like you have just one sample, right? can you show output of `adata.uns['spatial'].keys()` for both adatas - before and after c2l? Is there any chance you can share whole h5ad?
adata.uns['spatial'].keys()
before
dict_keys(['P1'])
after c2l
dict_keys(['P1'])

**Comment by iaaka** [comment]
Looks strange, I'm afraid I cannot solve it without access to data, can you share h5ad file? you can make adata.X=None (and maybe even adata.obsm=None) to reduce size.
Probably there is something wrong with parsing adata.obs, you can try not to copy c2l results there, maybe it can help...
