### ISSUE TITLE
h5ad2seurat Error in Matrix::sparseMatrix 'p' must be a nondecreasing vector

### ISSUE THREAD

**Issue by cosmiccapybara** [cellgeni/schard#8]
Hello, I am trying to convert a very large anndata object to Seurat. Any suggestions on how to fix "'p' must be a nondecreasing vector "? 
I did not generate the anndata object (I downloaded it from [http://catlas.org/catlas_downloads/humantissues/Cell_by_cCRE](http://catlas.org/catlas_downloads/humantissues/Cell_by_cCRE/matrix.mtx.gz)). Thanks in advance for your help.  

seu <- h5ad2seurat('matrix.h5ad')
The value -2^31 was detected in the dataset.
This has been converted to NA within R.
Error in Matrix::sparseMatrix(i = m$indices + 1, p = m$indptr, x = as.numeric(m$data),  : 
 'p' must be a nondecreasing vector c(0, ...)
 In addition: Warning message:
 In H5Dread(h5dataset = h5dataset, h5spaceFile = h5spaceFile, h5spaceMem = h5spaceMem,  :
NAs produced by integer overflow while converting 64-bit integer from HDF5 to a 32-bit integer in R.
Choose bit64conversion='bit64' or bit64conversion='double' to avoid data loss

**Comment by iaaka** [comment]
Hi @cosmiccapybara, unfortunately Seurat is unable to work with such a large datasets due to internal limitations of R, see [here](https://github.com/cellgeni/schard/issues/1) and [there](https://github.com/chanzuckerberg/cellxgene-census/issues/1095). There is a mention that Seurat v5 can potentially somehow work with such data, but no instructions are given. So for now we do not support datasets with more than 2^31 non-zero values.

**Comment by cosmiccapybara** [comment]
> Hi @cosmiccapybara, unfortunately Seurat is unable to work with such a large datasets due to internal limitations of R, see [here](https://github.com/cellgeni/schard/issues/1) and [there](https://github.com/chanzuckerberg/cellxgene-census/issues/1095). There is a mention that Seurat v5 can potentially somehow work with such data, but no instructions are given. So for now we do not support datasets with more than 2^31 non-zero values.

Thanks @iaaka. Just for reference, I was also not able to subset the object due to the error "Output dtype not compatible with inputs" (like in [anndata_issue_1140](https://github.com/scverse/anndata/issues/1140)).
